### ISSUE TITLE
Stellar Vanguard - sergeant melee options erroneously split up

### ISSUE THREAD

**Issue by crazytobuildmc** [dice-guild/vortex-gate-data#20]
![image](https://github.com/dice-guild/vortex-gate-data/assets/42681100/5bd40801-80a0-40e3-bc09-1dc8414cbc58)
This issue occurs with sergeants in vanguard, gravite vanguard, and scout squads (although since all scout models can be given a melee loadout, the sgt option can be outright removed). All other units including heroes appear to correctly replace their rifle with *both* a pistol and set of hand weapons.

**Comment by jaaimino** [comment]
This is fixed now
