### ISSUE TITLE
Strategies Adjustments

### ISSUE THREAD

**Issue by GreenyG** [dice-guild/vortex-gate-data#4]
Core: Quick Aim
should also apply to Bikers and Mounted units

Aeonweyr Sages: Mobility Training  
Should also apply to Bikers and Mounted units

Aeonweyr Sages: Expedient Retreat
Does this disengage a unit in melee?

**Comment by jaaimino** [comment]
Most strategies (now called tactics) now have no restrictions on the units they can be used on. Yes you can use the move to disengage but you'll still follow normal attack of opportunity rules for escaping combat
