### ISSUE TITLE
Aeonweyr Sages Lacking melee weapons and weapon errors

### ISSUE THREAD

**Issue by GreenyG** [dice-guild/vortex-gate-data#6]
Psychic on bike: 
energy_polearm not found

Champion on bike:
Plasma Grenade not found 

Lore keeper Assassin
Sniper Cannon (Sniper Mode) has the same range as (Suppression mode) and less range than ranger sniper rifles (18/36)

Aeonweyr bikers:
have no starting melee weapon, maybe energy knives?

Ranger biker Squad:
have no starting melee weapon, maybe elven blades?

Phantoms:
have no starting melee weapon, maybe give them Energy Weapon(2) since they seem CQC related with Fear, Ambush and low range weapons?

**Comment by jaaimino** [comment]
Aight most of this should be addressed now
