### ISSUE TITLE
Stellar Vanguard, Vanguard Bikesquad Reference mistake

### ISSUE THREAD

**Issue by GreenyG** [dice-guild/vortex-gate-data#8]
1x Vanguard Biker Sergeant equipped with (**Handweapon**, Marine Rifle, Twin Marine Rifle [Front]) with specials (Impact(1))
2x Vanguard Biker equipped with (**Handweapon**, Marine Rifle, Twin Marine Rifle [Front]) with specials (Impact(1))

Replace any model Marine Rifle and **Light Weapon** with Marine Pistol and Handweapon(2) for 2pts each

**Comment by jaaimino** [comment]
This should be fixed now
